#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Writes scripts/Client/Eos/EosKeys.g.cs (not committed) with the Epic Online Services product's keys, from a JSON file
({"productId", "sandboxId", "deploymentId", "clientId", "clientSecret"}) given as the argument, or from the environment
(EOS_PRODUCT_ID, EOS_SANDBOX_ID, EOS_DEPLOYMENT_ID, EOS_CLIENT_ID, EOS_CLIENT_SECRET). Without keys the game builds
without internet lobbies."""
import json, os, sys

names = ["productId", "sandboxId", "deploymentId", "clientId", "clientSecret"]
env = ["EOS_PRODUCT_ID", "EOS_SANDBOX_ID", "EOS_DEPLOYMENT_ID", "EOS_CLIENT_ID", "EOS_CLIENT_SECRET"]
keys = json.load(open(sys.argv[1])) if len(sys.argv) > 1 else {n: os.environ.get(e, "") for n, e in zip(names, env)}
missing = [n for n in names if not keys.get(n)]
if missing:
    sys.exit("missing EOS keys: " + ", ".join(missing))
here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, "..", "scripts", "Client", "Eos", "EosKeys.g.cs")
args = ", ".join(json.dumps(keys[n]) for n in names)
with open(out, "w") as f:
    f.write("// Generated by tools/eos_keys.py; not committed.\n#if ARCANUM_EOS\nnamespace Arcanum.Client.Eos;\n\n"
            "internal sealed partial record EosKeys\n{\n    static partial void Load(ref EosKeys? keys) => keys = new(" + args + ");\n}\n#endif\n")
print("wrote", os.path.normpath(out))
